In [39]:
import numpy as np
import pandas as pd

In [40]:
dry_beans = pd.read_excel ('Dry_Bean_Dataset.xlsx')

In [41]:
#print(dry_beans.size)
#dry_beans = dry_beans.drop(dry_beans[dry_beans["Class"] == "SEKER"].index)
#print(dry_beans.size)
#dry_beans = dry_beans.drop(dry_beans[dry_beans["Class"] == "BARBUNYA"].index)
#print(dry_beans.size)
#dry_beans = dry_beans.drop(dry_beans[dry_beans["Class"] == "BOMBAY"].index)
#print(dry_beans.size)
#dry_beans = dry_beans.drop(dry_beans[dry_beans["Class"] == "CALI"].index)
#print(dry_beans.size)
#dry_beans = dry_beans.drop(dry_beans[dry_beans["Class"] == "DERMASON"].index)
#Barbunya, Bombay, Cali, Dermosan, Horoz and Sira
#print(dry_beans.size)

In [42]:
dry_beans["Class"].replace({"HOROZ": 1, "SIRA": 2,"DERMASON": 3,"CALI": 4,"BOMBAY": 5,"BARBUNYA": 6,"SEKER": 7}, inplace=True)

In [43]:
dry_beans.drop(['Area', 'MajorAxisLength','MinorAxisLength', 'AspectRation',
                'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness',
                'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4'], axis=1, inplace=True)

In [44]:
dry_beans = dry_beans.reset_index(drop=True)
dry_beans

       Perimeter  Eccentricity  Class
0        610.291      0.549812      7
1        638.018      0.411785      7
2        624.110      0.562727      7
3        645.884      0.498616      7
4        620.134      0.333680      7
...          ...           ...    ...
13606    759.696      0.765002      3
13607    757.499      0.735702      3
13608    759.321      0.734065      3
13609    763.779      0.741055      3
13610    772.237      0.786693      3

[13611 rows x 3 columns]

In [45]:
#dry_beans.to_excel("Dry_Bean_Dataset_Complete.xlsx")

In [46]:
import random
for i in range(len(dry_beans)):
  if random.random() <= 0.96:
    dry_beans.loc[i,"Class"] = 0

dry_beans

       Perimeter  Eccentricity  Class
0        610.291      0.549812      0
1        638.018      0.411785      0
2        624.110      0.562727      0
3        645.884      0.498616      7
4        620.134      0.333680      0
...          ...           ...    ...
13606    759.696      0.765002      0
13607    757.499      0.735702      0
13608    759.321      0.734065      0
13609    763.779      0.741055      0
13610    772.237      0.786693      0

[13611 rows x 3 columns]

In [47]:
print(len(dry_beans[dry_beans["Class"] == 0]))
print(len(dry_beans[dry_beans["Class"] == 1]))
print(len(dry_beans[dry_beans["Class"] == -1]))

13070
81
0

In [48]:
dry_beans.to_excel("Dry_Bean_Dataset_All_Classes.xlsx")